#!/bin/bash

if ! [ -d "$HOME/storage/external-1" ];
then
    echo "No external SD card detected."
    echo "Skipping setting up extsd_id."
    echo ""
    exit 0

else
    if ! [ -f "$HOME/.extsd_id" ];
    then
        extsd_path=$(realpath "$HOME/storage/external-1")
        extsd_id=${extsd_path:9:9}

        echo $extsd_id > "$HOME/.extsd_id"
        echo "export EXT_SD=\"/storage/${extsd_id}\"" >> "$HOME/.environment"

        echo ""
        echo "- Added .extsd_id file with the SD card ID."
        echo "  Also, an EXT_SD variable has been added to .environment with its"
        echo "  full path (more confortable that writing '/storage/external-1')."
        echo ""
    fi
fi

