#!/bin/bash

function failed
{
    echo "Failed. Aborting."
    exit 1
}


if [ -f "$HOME/.virgl_ready" ];
then
    echo "VirGL already setup."
    exit 0
fi

APT_REPOS=$PREFIX/etc/apt/sources.list.d




echo "Setting up VirGL..."
echo "==================="

if ! [ -f ${APT_REPOS}/tur.list ];
then
    echo "Installing 'tur' repository ..."
    echo "==============================="
    echo ""

    pkg update
    pkg install -y tur-repo

    if ! [ "$?" == "0" ];
    then
        failed
    fi    
fi


echo ""
echo "Installing mesa, virgl and vulkan packages ..."
echo "=============================================="
echo ""

pkg install -y mesa-zink virglrenderer-mesa-zink vulkan-loader-android

if ! [ "$?" == "0" ];
then
    failed
fi


echo ""
echo "Downloading .virgl_environment config file ..."
echo "=============================================="
echo ""

URL=https://raw.githubusercontent.com/arithesage/termux_things
URL=$URL/refs/heads/main/termux-setup/.virgl_environment

wget $URL -O "$HOME/.virgl_environment"

if ! [ "$?" == "0" ];
then
    failed
fi

echo "source $HOME/.virgl_environment" >> $HOME/.bashrc


echo "VirGL setup finished"

touch $HOME/.virgl_ready

