#!/bin/bash

function failed
{
    echo "Failed. Aborting."
    exit 1
}




if [ -f "$HOME/.gl_already_setup" ];
then
    echo "VirGL already setup."
    exit 0
fi


echo "Setting up VirGL..."
echo "==================="
echo ""


APT_REPOS=$PREFIX/etc/apt/sources.list.d

if ! [ -f ${APT_REPOS}/tur.list ];
then
    pkg update
    pkg install -y tur-repo

    if ! [ "$?" == "0" ];
    then
        failed
    fi

    echo "- Installed 'tur' repository."
fi


pkg install -y mesa-zink virglrenderer-mesa-zink vulkan-loader-android


if ! [ "$?" == "0" ];
then
    failed
fi


echo "- Installed mesa, virgl and vulkan packages."

echo "source $HOME/.virgl_environment" >> $HOME/.bashrc
echo "" >> $HOME/.bashrc


echo "VirGL setup finished"

touch $HOME/.gl_already_setup

