#!/bin/bash

CMDLINE=$*

if ! [ "$EXT_SD" == "" ];
then
    SD_BINDING="--bind ${EXT_SD}:/mnt/extsd"
fi


proot-distro login ${PROOT_DISTRO} ${SD_BINDING} --user ${PROOT_USER} --shared-tmp -- ${CMDLINE}

