#!/bin/bash

EXE=$1
ARGS=$2

proot-distro login ${PROOT_DISTRO} --user ${PROOT_USER} --shared-tmp $HOME/scripts/enable_x11
proot-distro login ${PROOT_DISTRO} --user ${PROOT_USER} --shared-tmp $EXE $ARGS

