#!/bin/bash

function failed
{
    echo "Failed. Aborting."
    exit 1
}


export PROOT_DISTRO="ubuntu"
export PROOT_USER="puser"
PROOT_PATH="$PREFIX/var/lib/proot-distro/installed-rootfs/${PROOT_DISTRO}"

SCRIPTS=$HOME/scripts




if [ -f "$HOME/.proot_ready" ];
then
    echo "Proot distro already setup."
    echo ""
    exit 0
fi


if ! [ -d "$PROOT_PATH" ];
then
    if ! [ -f "${PREFIX}/bin/proot-distro" ];
    then
        echo "Installing proot-distro ..."
        echo "==========================="
        echo ""
        
        pkg update
        pkg install -y proot-distro

        if ! [ "$?" == "0" ];
        then
            failed
        fi
    fi


    echo ""
    echo "Installing ${PROOT_DISTRO} ..."
    echo "=============================="
    echo ""

    proot-distro install ${PROOT_DISTRO}

    if ! [ "$?" == "0" ];
    then
        failed
    fi


    echo "Preparing ${PROOT_DISTRO} ..."

    echo "Installing packages ..."
    echo "======================="
    echo ""

    $SCRIPTS/prun_admin apt-get update
    $SCRIPTS/prun_admin apt-get install -y gpg screen wget
    $SCRIPTS/prun_admin useradd --create-home --shell /bin/bash ${PROOT_USER}

    if ! [ "$?" == "0" ];
    then
        failed
    fi

    echo "Installing scripts ..."

    mkdir -p "$PROOT_PATH/root/scripts"

    cp "$SCRIPTS/enable_x11" "$PROOT_PATH/root/scripts"
    cp "$SCRIPTS/install_box86-64" "$PROOT_PATH/root/scripts"
    cp "$SCRIPTS/install_wine" "$PROOT_PATH/root/scripts"
    cp "$SCRIPTS/pexec" "$PROOT_PATH/usr/local/bin/"

    chmod +x "$PROOT_PATH/usr/local/bin/pexec"

    echo "source \$HOME/.environment" >> "$PROOT_PATH/root/.bashrc"
    echo "export PATH=\$PATH:\$HOME/scripts" >> "$PROOT_PATH/root/.environment"

    echo "export PROOT_DISTRO=\"${PROOT_DISTRO}\"" >> "$HOME/.environment"
    echo "export PROOT_PATH=\"${PROOT_PATH}\"" >> "$HOME/.environment"
    echo "export PROOT_USER=\"${PROOT_USER}\"" >> "$HOME/.environment"

    echo ""
    echo "Finished."

    touch "$HOME/.proot_ready"
fi

