#!/bin/bash

function failed
{
    echo "Failed. Aborting."
    echo ""
    exit 1
}


if [ -f "$HOME/.termux_setup_done" ];
then
    echo "Termux is already ready."
    echo ""
    exit 0
fi


BIN=$PREFIX/bin
SCRIPTS_REPO=https://raw.githubusercontent.com/arithesage/termux_things/\
             refs/heads/main/termux-setup/scripts




echo "Performing a basic Termux setup..."
echo "=================================="


if ! [ -f "$HOME/.bashrc" ];
then
    cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
    echo "- Added basic .bashrc file"
fi


if ! [ -f "$HOME/.environment" ];
then
    touch "$HOME/.environment"
    echo "source $HOME/.environment" >> "$HOME/.bashrc"
    
    echo "- Added .environment file"
fi


if ! [ -f "$BIN/sshd" ] || ! [ -f "$BIN/git" ];
then
    echo "- Proceeding with the installing of some packages..."
    echo ""

    pkg update

    echo ""
    echo "Installing OpenSSH and Wget..."
    echo "================================"
    echo ""

    pkg install -y openssh wget

    if ! [ "$?" == "0" ];
    then
        failed
    fi
fi


if ! [ -f "$HOME/scripts" ];
then
    echo ""
    echo "Installing some useful scripts..."
    echo "================================="
    echo ""

    mkdir "$HOME/scripts"

    SCRIPTS="$HOME/scripts"

    echo "export SCRIPTS=\"$HOME/scripts\"" >> "$HOME/.environment"
    echo "export PATH=\"$PATH:$SCRIPTS\"" >> "$HOME/.environment"

    wget $SCRIPTS_REPO/enable_x11 -O "$SCRIPTS/enable_x11"
    wget $SCRIPTS_REPO/find_extsd -O "$SCRIPTS/find_extsd"
    wget $SCRIPTS_REPO/install_box86-64 -O "$SCRIPTS/install_box86-64"
    wget $SCRIPTS_REPO/install_virgl -O "$SCRIPTS/install_virgl"
    wget $SCRIPTS_REPO/install_wine -O "$SCRIPTS/install_wine"
    wget $SCRIPTS_REPO/proot_admin -O "$SCRIPTS/proot_admin"
    wget $SCRIPTS_REPO/prun -O "$SCRIPTS/prun"
    wget $SCRIPTS_REPO/prun_admin -O "$SCRIPTS/prun_admin"
    wget $SCRIPTS_REPO/prun_x11 -O "$SCRIPTS/prun_x11"
    wget $SCRIPTS_REPO/setup_proot -O "$SCRIPTS/setup_proot"

    chmod -R +x $SCRIPTS
fi


if ! [ -d "$HOME/storage" ];
then
    echo "- Preparing storage access."
    echo -n "Please, grant permission when asked... "

    termux-setup-storage

    if ! [ "$?" == "0" ];
    then
        failed
    else
        echo "OK"        
    fi
fi

echo ""
echo "If you have a external SD card (a microSD), execute 'find_extsd'"
echo "command. It could be executed after termux-setup-storage, but"
echo "it seems always runs before storage folder is created, and so, it"
echo "doesn't find any 'external-1' folder (because there is none)."
echo ""

echo "Basic setup done. Enjoy Termux!"
touch "$HOME/.termux_setup_done"

