#!/bin/bash

if ! [ "$TERMUX_VERSION" == "" ];
then
    echo "This script is for Termux proot only."
    exit 1
fi


function failed
{
    echo "Installation failed!"
    echo ""
    exit 1
}


if [ -f "$HOME/.box86-64_ready" ];
then
    echo "Box86 and Box64 are already installed."
    echo ""
    exit 0
fi




if ! [ -d /usr/share/keyrings ];
then
    mkdir /usr/share/keyrings
fi




echo "Installing Box86..."
echo "==================="

if ! [ -f "/usr/share/keyrings/box86-archive-keyring.gpg" ];
then
    wget -qO- "https://pi-apps-coders.github.io/box86-debs/KEY.gpg" | \
    gpg --dearmor -o /usr/share/keyrings/box86-archive-keyring.gpg

    if ! [ "$?" == "0" ];
    then
        echo "Could not intall the GPG key."
        failed
    fi

    echo "- Added GPG key to keyrings."
fi


if ! [ -f "/etc/apt/sources/list.d/box86.sources" ];
then
    echo "Types: deb" > /var/tmp/box86.sources

    echo "URIs: https://Pi-Apps-Coders.github.io/box86-debs/debian" \
    >> /var/tmp/box86.sources

    echo "Suites: ./" >> /var/tmp/box86.sources
    echo "Signed-By: /usr/share/keyrings/box86-archive-keyring.gpg" \
    >> /var/tmp/box86.sources

    mv /var/tmp/box86.sources /etc/apt/sources.list.d/

    echo "- Added sources list for APT."
fi


if ! [ -f "/usr/local/bin/box86" ];
then
    dpkg --add-architecture armhf
    echo "- Enabled armhf architecture."

    echo "- Updating APT sources..."
    apt update
    
    echo "- Installing libc6 and box86-android ..."
    apt install -y libc6:armhf box86-android

    if ! [ "$?" == "0" ];
    then
        failed
    fi

    echo "Box86 for Android installed."
    echo ""
fi


echo "Installing Box64..."
echo "==================="

if ! [ -f "/usr/share/keyrings/box64-archive-keyring.gpg" ];
then
    wget -qO- "https://pi-apps-coders.github.io/box64-debs/KEY.gpg" | \
    gpg --dearmor -o /usr/share/keyrings/box64-archive-keyring.gpg

    if ! [ "$?" == "0" ];
    then
        echo "Could not intall the GPG key."
        failed
    fi

    echo "- Added GPG key to keyrings."
fi


if ! [ -f "/etc/apt/sources/list.d/box64.sources" ];
then
    echo "Types: deb" > /var/tmp/box64.sources

    echo "URIs: https://Pi-Apps-Coders.github.io/box64-debs/debian" \
    >> /var/tmp/box64.sources

    echo "Suites: ./" >> /var/tmp/box64.sources
    echo "Signed-By: /usr/share/keyrings/box64-archive-keyring.gpg" \
    >> /var/tmp/box64.sources

    mv /var/tmp/box64.sources /etc/apt/sources.list.d/

    echo "- Added sources list for APT."
fi


if ! [ -f "/usr/local/bin/box64" ];
then
    dpkg --add-architecture arm64
    echo "- Enabled arm64 architecture."

    echo "- Updating APT sources..."
    apt update
    
    echo "- Installing box64-android ..."
    apt install -y box64-android

    if ! [ "$?" == "0" ];
    then
        failed
    fi

    echo "Box64 for Android installed."
    echo ""
fi


echo "Finished!"
echo ""

touch $HOME/.box86-64_ready

